name: Deploy Python Package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v1

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Set Poetry config
        run: |
          poetry config pypi-token.pypi "${{ secrets.PYPI_TOKEN }}"

      - name: Build
        run: poetry build

      - name: Publish
        run: poetry publish
